name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name: CI + Sonar + Docker Build
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # 1) CHECKOUT
      # -------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # necessário para sonar

      # -------------------------------
      # 2) INSTALL DEPENDENCIES
      # -------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # -------------------------------
      # 3) TESTS
      # -------------------------------
      - name: Run Tests
        run: npm test --if-present

      # -------------------------------
      # 4) SONARCLOUD (SAST)
      # -------------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: '.'

      - name: Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # -------------------------------
      # 5) BUILD DA APLICAÇÃO
      # -------------------------------
      - name: Build App
        run: npm run build --if-present

      # -------------------------------
      # 6) VERSIONAMENTO (pega versão do package.json)
      # -------------------------------
      - name: Get version from package.json
        id: version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      # -------------------------------
      # 7) LOGIN DOCKER HUB
      # -------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------------------------------
      # 8) BUILD IMAGEM DOCKER
      # -------------------------------
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-sast:${{ steps.version.outputs.version }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-sast:${{ steps.version.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/api-sast:latest

      # -------------------------------
      # 9) PUSH IMAGEM PARA DOCKER HUB
      # -------------------------------
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api-sast:${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/api-sast:latest
